services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:80"
    environment:
      - UNSPLASH_CLIENT_ID=${UNSPLASH_CLIENT_ID}
      - UNSPLASH_REDIRECT_URI=${UNSPLASH_REDIRECT_URI}
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build:
      