services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
